MAIN_DIR	= example

FC		= /usr/local/Packages/mvapich2-tcp-intel-1.2rc2/bin/mpif90
FORTRAN_FLAGS	=
INCLUDE		=
LIB_DIR		=
LIBS		=

LD		= ld
LD_FLAGS       	= 
LD_SHARED	= -shared

MAKE		= make
 
RM		= rm -rf

